### PR TITLE
merge data upto 2019 to 2020 and create main_data for use of project

### PR DESCRIPTION
**Pull request by Jill208**
Kindly accept the merge request after review of my code

### CODE REVIEW

**Comment by Jill208** [comment]
Yeah! as a CEO and co-founder of Bhanderi bros software LLC I accept the request

**Review by Jill208 — COMMENTED** [review]
fine!!

**Review by 08-zeel — APPROVED** [review]
i approve

**Review by tirthtnp8102 — APPROVED** [review]
I Approve.

**Pull request merged**
